site_name: My Project Site
site_description: Documentation and project overview

theme:
  name: material

nav:
  - Home: index.md
  - Week 1:
      - Website Creation: week1/monday.md
      - Introduction: week1/intro.md
      - Setup: week1/setup.md
  - Week 2:
      - Overview: week2/index.md
      - Analysis: week2/analysis.md
      - Results: week2/results.md
  - Week 3:
      - Overview: week3/index.md
  - Week 4:
      - Overview: week4/index.md